'use client';
import './globals.css'
import { Poppins } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext'

const inter = Poppins({ subsets: ['latin'] , weight:'400'})

export const metadata = {
  title: 'Google Docs Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthContextProvider>
        {children}
      </AuthContextProvider>
        </body>
    </html>
  )
}
